-- Giga Watt
-- Iteration 002 — Platform User
--
-- User является сущностью Платформы и не смешивается
-- с Employee из предметной модели предприятия.
--
-- Связь User -> Employee на текущем этапе определяется
-- через employee_emails.email на уровне application/loader.
-- Обязательный FK users -> employees не создаётся.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    is_superuser BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT users_email_unique UNIQUE (email)
);
